---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller
  namespace: image-clone-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: controller-role-binding
subjects:
- kind: ServiceAccount
  name: controller
  namespace: image-clone-controller
roleRef:
  kind: ClusterRole
  name: controller-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: controller-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments", "daemonsets"]
  verbs: ["list", "watch", "update"]
- apiGroups: [""]
  resources: ["secrets","serviceaccounts"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create","patch"]
