# permissions for end users to edit imagecloners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imagecloner-editor-role
rules:
- apiGroups:
  - apps.mriyam.com
  resources:
  - imagecloners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.mriyam.com
  resources:
  - imagecloners/status
  verbs:
  - get
